# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Deploy VitePress site to Pages

on:
  push:
    branches: [main] # Update this if you're using a different default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Use 0 to fetch all history, or adjust as needed
      # Uncomment the appropriate setup action if using pnpm or Bun
      # - uses: pnpm/action-setup@v2 # pnpm setup
      # - uses: oven-sh/setup-bun@v1 # Bun setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm # or pnpm / yarn
      - name: Install dependencies
        run: npm ci # or pnpm install / yarn install / bun install
      - name: Build VitePress site
        run: npm run build # or pnpm docs:build / yarn docs:build / bun run docs:build
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
